name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
      resource_deployment:
        type: choice
        description: Select the Terraform Module to Deploy it
        default: 'vpc'
        options:
        - github-runner
        - vpc
        - rds
    
jobs:
  validate-terraform-resources:
    runs-on: [self-hosted]

    defaults:
      run: 
        working-directory: modules/${{ inputs.resource_deployment }}/

    steps:
      - uses: actions/checkout@v3

      - name: Terraform Init
        id: init
        run: |
            echo "${{ inputs.resource_deployment }} Initialization"
            terraform init -backend-config='key=${{ inputs.env }}/${{ inputs.resource_deployment }}/terraform.tfstate'

      - name: Terraform Apply
        run: |
            echo "${{ inputs.resource_deployment }} Terraform Apply"
            terraform apply -auto-approve -input=false -var-file=${{ inputs.env }}.tfvars